apiVersion: v1
kind: Service
metadata:
  name: notificacao-ms
  namespace: fixit
  labels:
    app: notificacao-ms
spec:
  type: NodePort
  selector:
    app: notificacao-ms
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      nodePort: 30084
      protocol: TCP
